import Link from "next/link";
import Image from "next/image";

const spaces = [
  { title: "Flexible desks", copy: "Drop in, settle down, and get your best work done.", price: "From ₹750 / day", image: "https://images.unsplash.com/photo-1596626586362-c27d6ad37b08?auto=format&fit=crop&w=900&q=85" },
  { title: "Private cabins", copy: "Quiet rooms for focused days and small teams.", price: "From ₹1,200 / day", image: "https://images.unsplash.com/photo-1704364610940-52b509d3951f?auto=format&fit=crop&w=900&q=85" },
  { title: "Meeting rooms", copy: "Bring people together in rooms that work hard.", price: "From ₹600 / hour", image: "https://images.unsplash.com/photo-1690191863988-f685cddde463?auto=format&fit=crop&w=900&q=85" },
];

export default function Home() {
  return <main className="homepage">
    <nav className="homepage-nav"><Link className="homepage-brand" href="/"><span>N</span><strong>NookOS</strong></Link><div className="homepage-links"><a href="#spaces">Spaces</a><a href="#experience">Experience</a><a href="#amenities">Amenities</a><a href="#visit">Visit us</a></div><div className="homepage-actions"><Link href="/login" className="homepage-signin">Member sign in</Link><Link href="/user/book-a-space" className="homepage-nav-cta">Book a space <span>↗</span></Link></div></nav>
    <section className="homepage-hero"><div className="homepage-hero-copy"><p className="homepage-eyebrow">◦ FOUNDRY DISTRICT · BENGALURU</p><h1>A better place to do your best work.</h1><p className="homepage-lede">One thoughtfully designed workspace for focused days, ambitious teams, and a community worth knowing.</p><div className="homepage-hero-actions"><Link href="/user/book-a-space" className="homepage-button homepage-button-primary">Book a tour <span>↗</span></Link><a href="#spaces" className="homepage-button homepage-button-secondary">Explore spaces</a></div><div className="homepage-meta"><span>◷ Open daily · 7 AM–10 PM</span><span>₹ Day passes from ₹750</span></div></div><div className="homepage-hero-media"><Image fill sizes="(max-width: 760px) 100vw, 55vw" src="https://images.unsplash.com/photo-1604328698692-f76ea9498e76?auto=format&fit=crop&w=1400&q=85" alt="Bright coworking workspace"/><div className="homepage-availability"><div><strong>Today at Foundry District</strong><span className="homepage-live">● LIVE</span></div><p>18 desks · 4 cabins · 3 meeting rooms available</p></div></div></section>
    <section className="homepage-proof"><strong>Work well, together.</strong><span><b>180+</b> workstations</span><span><b>12</b> meeting rooms</span><span><b>2,400+</b> members served</span><span><b>4.9/5</b> member rating</span></section>
    <section id="spaces" className="homepage-section homepage-spaces"><div className="homepage-section-heading"><div><p className="homepage-eyebrow">SPACES THAT FIT THE DAY</p><h2>Choose your pace.</h2></div><a href="#spaces">View all spaces ↗</a></div><div className="homepage-space-rail">{spaces.map((space) => <article className="homepage-space-card" key={space.title}><Image width={900} height={520} sizes="(max-width: 760px) 82vw, 33vw" src={space.image} alt=""/><div><h3>{space.title}</h3><p>{space.copy}</p><span>{space.price}</span></div></article>)}</div></section>
    <section id="experience" className="homepage-experience"><Image width={1200} height={800} sizes="(max-width: 760px) 100vw, 55vw" src="https://images.unsplash.com/photo-1587614203976-365c74645e83?auto=format&fit=crop&w=1200&q=85" alt="People collaborating in a lounge"/><div><p className="homepage-eyebrow">THE NOOKOS EXPERIENCE</p><h2>Work with calm focus. Stay for the people.</h2><p>From the first coffee to the last call, Foundry District is designed around how work actually happens—with calm focus zones, useful hospitality, and people who know your name.</p><Link href="/user/community">Discover the community ↗</Link></div></section>
    <section id="amenities" className="homepage-section homepage-amenities"><div className="homepage-section-heading"><div><p className="homepage-eyebrow">EVERYTHING YOU NEED</p><h2>Small details, considered.</h2></div></div><div className="homepage-amenity-grid"><article><span>☕</span><h3>Good coffee</h3><p>Freshly brewed, always within reach.</p></article><article><span>◉</span><h3>Fast Wi-Fi</h3><p>Reliable connection from desk to lounge.</p></article><article><span>♧</span><h3>Community</h3><p>People, events, and conversations worth having.</p></article><article><span>♧</span><h3>Thoughtful support</h3><p>A team that makes your day easier.</p></article></div></section>
    <section className="homepage-testimonial"><p>“The kind of place that makes you want to come in early—and stay a little later.”</p><span>— Mira Shah · Northstar Labs</span></section>
    <section id="visit" className="homepage-cta"><div><p className="homepage-eyebrow">COME SEE THE SPACE</p><h2>Your next great workday starts here.</h2><p>Tour Foundry District, meet the team, and find the setup that fits how you work.</p></div><div><Link href="/user/book-a-space" className="homepage-button homepage-button-primary">Book your tour</Link><a href="#spaces" className="homepage-button homepage-button-secondary">Buy a day pass</a></div></section>
    <footer className="homepage-footer"><div><Link className="homepage-brand" href="/"><span>N</span><strong>NookOS</strong></Link><p>Foundry District · Bengaluru</p></div><div><a href="mailto:hello@nookos.work">hello@nookos.work</a><a href="#spaces">Spaces</a><Link href="/login">Member sign in</Link></div><small>© 2024 NookOS</small></footer>
  </main>;
}
